image: ubuntu_nvm

matrix:
  - env: SCRIPT=test NODE_VERSION=8
  - env: SCRIPT=test NODE_VERSION=10
  - env: SCRIPT=test NODE_VERSION=12
  - env: SCRIPT=test NODE_VERSION=14

before_install:
  - nvm install $NODE_VERSION
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi

cache:
  - node_modules
